const params = {
  SENSOR_POWER: 2,
  SENSOR_MULTIPLIER: 0.00035,
  TILT_MULTIPLIER: 1,
  CAMERA_TILT_MULTIPLIER: 5,
  INITIAL_SPEED: 380,
  BOOSTED_SPEED: 700,
  BOOSTED_SPEED_INTERVAL: 1500,
  REDUCED_SPEED: 100,
  REDUCED_SPEED_INTERVAL: 500,
  INITIAL_NITROS: 1,
};

export default params;
